import sys
import os
sys.path.insert(0, os.path.abspath('../../obsidian'))

# Configuration file for the Sphinx documentation builder.

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'obsidian'
copyright = 'Merck & Co., Inc., Rahway, NJ, USA and its affiliates. All rights reserved.'
author = 'Kevin Stone, Yuting Xu'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosummary',
    'myst_parser',
]

myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filename
source_suffix = [".rst", ".md"]  # Do NOT include ipynb

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# Default options for autodoc directives. Applied to all autodoc directives
autodoc_default_options = {
    "member-order": "groupwise",
}

autodoc_default_options = {'members': None,  # shows all members
                           'show-inheritance': True}

autodoc_typehints = "signature"
autoclass_content = "class"  # Use class docstring instead of __init__

# Autosummary Options
autosummary_imported_members = False
autosummary_ignore_module_all = True
suppress_warnings = [
    'autosummary.import_cycle',
]

# Ignore Jupyter Lab checkpoint folders
exclude_patterns = ['**.ipynb_checkpoints']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
  "collapse_navigation": True,
  "logo": {
      "alt_text": "obsidian - Home",
      "text": "obsidian APO",
      "image_light": "_static/obsidian_logo.svg",
      "image_dark": "_static/obsidian_logo_dark.svg",
  },
  "icon_links": [
      {
        "name": "GitHub",
        "url": "https://github.com/MSDLLCpapers/obsidian/",
        "icon": "fa-brands fa-github",
        "type": "fontawesome",
      },
      {
         "name": "PyPI",
         "url": "https://pypi.org/project/obsidian-apo/",
         "icon": "fa-brands fa-python",
         "type": "fontawesome",
      },
  ],
  "analytics": {
        "google_analytics_id": "G-BPMFV2DMZE",
  },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["mycss.css"]
html_favicon = "_static/obsidian_logo.svg"

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True
