name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        pip install --index-url https://download.pytorch.org/whl/cpu --extra-index-url https://pypi.org/simple ".[dev]" pytest-xdist[psutil]
    - name: Run tests and collect coverage
      run: pytest -n logical --cov=obsidian --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --index-url https://download.pytorch.org/whl/cpu --extra-index-url https://pypi.org/simple .[docs]
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - uses: astral-sh/ruff-action@v4.1.0
      - name: Ruff Lint (critical errors only for now before enforce a formatter)
        run: ruff check .
      - name: Ruff Format Check
        run: ruff format --check . || true
